### ISSUE TITLE
gnb不能在树霉派+ubuntu 18.04上部署

### ISSUE THREAD

**Issue by wilesun** [gnbdev/gnb_udp_over_tcp#1]
树霉派3b,装ubuntu 18.04，然后取gnb的代码。
cp gnb_initkey_linux_x86_64.sh gnb_initkey_raspberryARMv7.sh
nano gnb_initkey_raspberryARMv7.sh

#GNB_BINARY=Linux_x86_64
GNB_BINARY=raspberrypi_ARMv7
保存修改后,执行gnb_initkey_raspberryARMv7.sh，生成key失败

放弃这种方式，将x86_64上的conf完整复制过来，重新init
./sh/gnb_raspberrypi_ARMv7.sh debug 1003，结果失败

**Comment by wilesun** [comment]
抱歉，gnb的issue提到这里。gnb没法提issue

**Comment by gnbdev** [comment]
没看到失败的提示，无法判断。

**Comment by gnbdev** [comment]
我大致猜到原因，现在编译的树莓派版本是官方的操作系统，运行时应该跟树莓派的ubuntu 18.04不一样。
